# Generated by Django 2.1 on 2018-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(default='/media/null', upload_to='publicacoes', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='mensagem',
            field=models.TextField(help_text='Digite uma mensagem', verbose_name='Mensagem'),
        ),
    ]
