# Generated by Django 2.1 on 2018-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_auto_20180918_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(default='', help_text='Digite um título', max_length=30, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(default='publicacoes/null.png', upload_to='publicacoes', verbose_name='Imagem'),
        ),
    ]
