# Generated by Django 2.1 on 2018-09-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Atracao',
        ),
    ]
