# Generated by Django 2.1 on 2018-09-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0002_auto_20180912_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'Atração', 'verbose_name_plural': 'Atrações'},
        ),
        migrations.RemoveField(
            model_name='atracao',
            name='age',
        ),
        migrations.RemoveField(
            model_name='atracao',
            name='last_name',
        ),
        migrations.AddField(
            model_name='atracao',
            name='bio',
            field=models.TextField(null=True, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='atracao',
            name='foto',
            field=models.ImageField(default='Uma breve descrição sobre a atração.', upload_to='', verbose_name='Foto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atracao',
            name='profissao',
            field=models.CharField(default='Uma breve descrição sobre a atração.', max_length=30, verbose_name='Profissão'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atracao',
            name='site',
            field=models.URLField(default='instagram.com', verbose_name='Mais'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atracao',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Primeiro Nome'),
        ),
    ]
