# Generated by Django 2.1 on 2018-09-12 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0004_auto_20180912_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='first_name',
            new_name='name',
        ),
    ]
