# Generated by Django 2.1 on 2018-09-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0005_auto_20180912_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='foto',
            field=models.ImageField(upload_to='atracoes', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='site',
            field=models.URLField(default='https://instagram.com/', verbose_name='Site'),
        ),
    ]
